x-default-environment: &default-environment
  TZ: "UTC"
  NODE_ENV: development
  DB_HOST: db
  DB_USER: sa
  DB_NAME: idp_development
  DB_PASS: &default-db-password DevPwd99!
  DB_PORT: &default-db-port 1433
  FRONTEND_URL: "http://localhost:8080"
  VITE_APPLICATION_NAME: "Internal Data Portal"
  VITE_API_BASE_URL: "http://localhost:3000"
  VITE_AUTH0_CLIENT_ID: "ZHjPOeCwYBov6eR1lxGOVYhYi4VPV8eU"
  VITE_AUTH0_AUDIENCE: "testing"
  VITE_AUTH0_DOMAIN: "https://dev-0tc6bn14.eu.auth0.com"
  RELEASE_TAG: "${RELEASE_TAG:-development}"
  GIT_COMMIT_HASH: "${GIT_COMMIT_HASH:-not-set}"
  MAIL_HOST: "mail"
  MAIL_PORT: 1025
  MAIL_FROM: "idp.development@yukon.ca"

services:
  api:
    build:
      context: ./api
      dockerfile: development.Dockerfile
    env_file:
      - ./api/.env.development
    environment:
      <<: *default-environment
    tty: true # allows attaching debugger, equivalent of docker exec -t
    # stdin_open: true # equivalent of docker exec -i
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/api
      - ./.gitignore:/usr/src/.gitignore
      - ./.prettierrc.yaml:/usr/src/.prettierrc.yaml
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: ./web
      dockerfile: development.Dockerfile
    environment:
      <<: *default-environment
    ports:
      - "8080:8080"
    volumes:
      - ./web:/usr/src/web
      - ./.gitignore:/usr/src/.gitignore
      - ./.prettierrc.yaml:/usr/src/.prettierrc.yaml
    depends_on:
      - api

  test_api:
    build:
      context: ./api
      dockerfile: development.Dockerfile
    command: /bin/true
    env_file:
      - ./api/.env.development
    environment:
      <<: *default-environment
      NODE_ENV: test
      DB_NAME: idp_test
    tty: true
    volumes:
      - ./api:/usr/src/api
    depends_on:
      db:
        condition: service_healthy

  test_web:
    build:
      context: ./web
      dockerfile: development.Dockerfile
    command: /bin/true
    environment:
      <<: *default-environment
      NODE_ENV: test
    tty: true
    volumes:
      - ./web:/usr/src/web

  db:
    image: mcr.microsoft.com/mssql/server:2022-CU13-ubuntu-22.04
    user: root
    environment:
      <<: *default-environment
      DB_HOST: "localhost"
      MSSQL_SA_PASSWORD: *default-db-password
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql/data
    healthcheck:
      # Ensures that server is started and that "idp_development" database is in an "online" state.
      # https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-databases-transact-sql?view=sql-server-2017
      test: |
        sh -c '
          /opt/mssql-tools/bin/sqlcmd \
          -h -1 \
          -t 1 \
          -U sa \
          -P "$$MSSQL_SA_PASSWORD" \
          -Q "SET NOCOUNT ON; Select SUM(state) from sys.databases WHERE name = '$$DB_NAME'"
        '
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s

  mail:
    image: maildev/maildev
    user: root
    ports:
      - "1080:1080" # Web UI
      - "1025:1025" # SMTP

  # For easily generating large PlantUML diagrams
  # Not relevant to production environment.
  # Accessible at http://localhost:9999
  # plantuml:
  #   image: plantuml/plantuml-server:jetty
  #   ports:
  #     - 9999:8080
  #   environment:
  #     PLANTUML_LIMIT_SIZE: 8192

volumes:
  db_data:
